/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BiometricDataService } from "../biometricData.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BiometricDataCreateInput } from "./BiometricDataCreateInput";
import { BiometricData } from "./BiometricData";
import { BiometricDataFindManyArgs } from "./BiometricDataFindManyArgs";
import { BiometricDataWhereUniqueInput } from "./BiometricDataWhereUniqueInput";
import { BiometricDataUpdateInput } from "./BiometricDataUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BiometricDataControllerBase {
  constructor(
    protected readonly service: BiometricDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BiometricData })
  @nestAccessControl.UseRoles({
    resource: "BiometricData",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBiometricData(
    @common.Body() data: BiometricDataCreateInput
  ): Promise<BiometricData> {
    return await this.service.createBiometricData({
      data: data,
      select: {
        biometricType: true,
        createdAt: true,
        facialRecognition: true,
        fingerprint: true,
        id: true,
        irisScan: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BiometricData] })
  @ApiNestedQuery(BiometricDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BiometricData",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async biometricDataItems(
    @common.Req() request: Request
  ): Promise<BiometricData[]> {
    const args = plainToClass(BiometricDataFindManyArgs, request.query);
    return this.service.biometricDataItems({
      ...args,
      select: {
        biometricType: true,
        createdAt: true,
        facialRecognition: true,
        fingerprint: true,
        id: true,
        irisScan: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BiometricData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BiometricData",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async biometricData(
    @common.Param() params: BiometricDataWhereUniqueInput
  ): Promise<BiometricData | null> {
    const result = await this.service.biometricData({
      where: params,
      select: {
        biometricType: true,
        createdAt: true,
        facialRecognition: true,
        fingerprint: true,
        id: true,
        irisScan: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BiometricData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BiometricData",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBiometricData(
    @common.Param() params: BiometricDataWhereUniqueInput,
    @common.Body() data: BiometricDataUpdateInput
  ): Promise<BiometricData | null> {
    try {
      return await this.service.updateBiometricData({
        where: params,
        data: data,
        select: {
          biometricType: true,
          createdAt: true,
          facialRecognition: true,
          fingerprint: true,
          id: true,
          irisScan: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BiometricData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BiometricData",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBiometricData(
    @common.Param() params: BiometricDataWhereUniqueInput
  ): Promise<BiometricData | null> {
    try {
      return await this.service.deleteBiometricData({
        where: params,
        select: {
          biometricType: true,
          createdAt: true,
          facialRecognition: true,
          fingerprint: true,
          id: true,
          irisScan: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
