/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AuthenticationLogService } from "../authenticationLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuthenticationLogCreateInput } from "./AuthenticationLogCreateInput";
import { AuthenticationLog } from "./AuthenticationLog";
import { AuthenticationLogFindManyArgs } from "./AuthenticationLogFindManyArgs";
import { AuthenticationLogWhereUniqueInput } from "./AuthenticationLogWhereUniqueInput";
import { AuthenticationLogUpdateInput } from "./AuthenticationLogUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AuthenticationLogControllerBase {
  constructor(
    protected readonly service: AuthenticationLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AuthenticationLog })
  @nestAccessControl.UseRoles({
    resource: "AuthenticationLog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAuthenticationLog(
    @common.Body() data: AuthenticationLogCreateInput
  ): Promise<AuthenticationLog> {
    return await this.service.createAuthenticationLog({
      data: data,
      select: {
        authenticationMethod: true,
        citizenId: true,
        createdAt: true,
        id: true,
        result: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AuthenticationLog] })
  @ApiNestedQuery(AuthenticationLogFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AuthenticationLog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authenticationLogs(
    @common.Req() request: Request
  ): Promise<AuthenticationLog[]> {
    const args = plainToClass(AuthenticationLogFindManyArgs, request.query);
    return this.service.authenticationLogs({
      ...args,
      select: {
        authenticationMethod: true,
        citizenId: true,
        createdAt: true,
        id: true,
        result: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AuthenticationLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthenticationLog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authenticationLog(
    @common.Param() params: AuthenticationLogWhereUniqueInput
  ): Promise<AuthenticationLog | null> {
    const result = await this.service.authenticationLog({
      where: params,
      select: {
        authenticationMethod: true,
        citizenId: true,
        createdAt: true,
        id: true,
        result: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AuthenticationLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthenticationLog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAuthenticationLog(
    @common.Param() params: AuthenticationLogWhereUniqueInput,
    @common.Body() data: AuthenticationLogUpdateInput
  ): Promise<AuthenticationLog | null> {
    try {
      return await this.service.updateAuthenticationLog({
        where: params,
        data: data,
        select: {
          authenticationMethod: true,
          citizenId: true,
          createdAt: true,
          id: true,
          result: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AuthenticationLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthenticationLog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAuthenticationLog(
    @common.Param() params: AuthenticationLogWhereUniqueInput
  ): Promise<AuthenticationLog | null> {
    try {
      return await this.service.deleteAuthenticationLog({
        where: params,
        select: {
          authenticationMethod: true,
          citizenId: true,
          createdAt: true,
          id: true,
          result: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
